### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [nathanclevenger/gpt-markdown-cli#1]
- [ ] Support Blogs
- [ ] Support Landing Pages
- [ ] Support Documentation
- [ ] Support Books
- [ ] Support Email Sequences
- [ ] Support Newsletters
- [ ] Support Slide Decks
- [ ] Support Video Scripts
- [ ] Support Custom Lists
- [ ] Support Custom Content
- [ ] Support Audiences & Tone
